languageCode = "en"
languageName = "English"
weight = 1
title = "BBAGWANG"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/main_logo.png"
  secondaryLogo = "img/main_logo.png"
  description = "BBAGWANG"
  copyright = "Copyright 2023. BBAGWANG all rights reserved."

[author]
  name = "BBAGWANG"
  image = "img/bbagwang.png"
  headline = "N00b"
  bio = "Lazy Perfectionist"
  links = [
    { email = "mailto:bbagwang@gmail.com" },
    { link = "https://bbagwang.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
    { discord = "https://discord.gg/tjR4Q5yY4n" },
#     { dribbble = "https://dribbble.com/username" },
    { facebook = "https://facebook.com/bbagwangs" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/bbagwang" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
    { instagram = "https://instagram.com/bbagwang" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/bbagwang" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    { steam = "https://steamcommunity.com/id/bbagwang/" },
#     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
    { twitter = "https://twitter.com/bbagwang" },
#     { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://youtube.com/@user-ln4cd6xo1h" },
#     { ko-fi = "https://ko-fi.com/username" },
  ]
